### ISSUE TITLE
Mess with russian letters in text tool when typing in Russian

### ISSUE THREAD

**Issue by vitiok78** [DamirPorobic/kImageAnnotator#59]
Pop Os (Ubuntu 19.04 branch), Gnome 3.32.1
Ksnip version 1.6.0-continuous
Build 737-bd78ccf (same issue in previous builds)

Some letters are in Latin or even not showed when typing in Russian
There should be **"Не работает на русском языке"**
![image](https://user-images.githubusercontent.com/6100293/58172786-2e02ea80-7ca2-11e9-830a-a118446e7de0.png)

**Comment by DamirPorobic** [comment]
Could it be that only Shortcut Keys are affected, either entered as Latin letters or missing completely? 
Shortcut Keys are: S, P, N, J, K, M, T, A, D, L, B, R, E

**Comment by DamirPorobic** [comment]
Just tested with disabled shortcuts, this is what I get when I typ on my keyboard: 
QWERTZUIOÜ (First row of letters)
![image](https://user-images.githubusercontent.com/12796236/64100386-c6157300-cd6b-11e9-9dff-d41283fdff46.png)
Is that what you would expect?

**Comment by vitiok78** [comment]
I've recorded a video representing this issue
https://youtu.be/fjuCKglKpg4

**Comment by DamirPorobic** [comment]
Thanks, I think I've got the issue and a fix for it. I hope I can push it by the end of the day

**Comment by DamirPorobic** [comment]
I believe this is fixed now. Can you please test?

**Comment by vitiok78** [comment]
I've updated only kimageannotator but ksnip stopped working.

**Comment by vitiok78** [comment]
Trying to rebuild ksnip but there are errors
/****************************************************************************/
[  5%] Building CXX object src/CMakeFiles/ksnip.dir/main.cpp.o
In file included from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/X11ImageGrabber.h:25,
                 from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/ImageGrabberFactory.h:28,
                 from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/main.cpp:29:
/home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/X11Wrapper.h:34:2: error: ‘ImageWithPosition’ does not name a type
   34 |  ImageWithPosition getCursorWithPosition() const;
      |  ^~~~~~~~~~~~~~~~~
In file included from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/ImageGrabberFactory.h:28,
                 from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/main.cpp:29:
/home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/X11ImageGrabber.h:38:2: error: ‘ImageWithPosition’ does not name a type
   38 |  ImageWithPosition getCursorWithPosition() const override;
      |  ^~~~~~~~~~~~~~~~~
In file included from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/ImageGrabberFactory.h:29,
                 from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/main.cpp:29:
/home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/KdeWaylandImageGrabber.h:47:2: error: ‘ImageWithPosition’ does not name a type
   47 |  ImageWithPosition getCursorWithPosition() const override;
      |  ^~~~~~~~~~~~~~~~~
In file included from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/ImageGrabberFactory.h:30,
                 from /home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/main.cpp:29:
/home/vitiok78/.cache/yay/ksnip-git/src/ksnip/src/backend/imageGrabber/GnomeWaylandImageGrabber.h:40:2: error: ‘ImageWithPosition’ does not name a type
   40 |  ImageWithPosition getCursorWithPosition() const override;
      |  ^~~~~~~~~~~~~~~~~
make[2]: *** [src/CMakeFiles/ksnip.dir/build.make:105: src/CMakeFiles/ksnip.dir/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: src/CMakeFiles/ksnip.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
==> ERROR: A failure occurred in build().
    Aborting...
Error making: ksnip-git

**Comment by DamirPorobic** [comment]
You probably were not able to test anything as I've broke the build. It should be working again.

**Comment by vitiok78** [comment]
If you posted it on Arch's AUR, that would be awesome!

**Comment by DamirPorobic** [comment]
Not sure what you mean? Talking about making the version available or about this issue here? 
There is a discussion on the AUR package but more in direction posting only the stable version, which is currently 1.5.0 -> https://aur.archlinux.org/packages/ksnip-git/

**Comment by vitiok78** [comment]
I mean the ability to have both versions on AUR. One for stable 1.5.0 and one for the latest work in progress 1.6.0.

**Comment by DamirPorobic** [comment]
Yeah, that must come from the packager @dracorp, you must ask him if something like that is possible or recommend, I only write the software.

**Comment by DamirPorobic** [comment]
For testing purpose you could quickly try out the appImage, which doesn't require installation.

**Comment by vitiok78** [comment]
I want to test all.
So... I've build from source kColorPicker, kImageAnnotator, but when building ksnip, there's an error:
```
[ 84%] Linking CXX executable ksnip
/usr/bin/ld: cannot find -lkImageAnnotator
collect2: error: ld returned 1 exit status
make[2]: *** [src/CMakeFiles/ksnip.dir/build.make:1027: src/ksnip] Error 1
make[1]: *** [CMakeFiles/Makefile2:129: src/CMakeFiles/ksnip.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by vitiok78** [comment]
Appimage version works like a charm! There's no issue with russian letters anymore

**Comment by DamirPorobic** [comment]
Awesome! The other issue with the installation is probably due to having kImageAnnotator installed twice, once via the usual packaging and once with cmake and this might be causing this issue, but that is just a guess. Lets wait for the package to become available and meanwhile you can use the appImage if that's ok for you. I'll be closing this bug then.

**Comment by vitiok78** [comment]
Great Work! Thank you! The best screenshot app!

**Comment by DamirPorobic** [comment]
Glad you like it :)
